language: php

os: linux

php:
  - 7.2
  - 7.3
  - 7.4

env:
  - APP_ENV=testing DB_CONNECTION=mysql DB_DATABASE=travis_db DB_USERNAME=travis DB_PASSWORD= CACHE_DRIVER=array SESSION_DRIVER=array QUEUE_DRIVER=sync

addons:
  code_climate:
    repo_token: 54ec5b2043e1879fa0c7ca5625923300bd2eebffc679b2e106ff286968bdad2e

# cache vendor dirs
cache:
  directories:
    - vendor
    - $HOME/.composer/cache

install:
  - COMPOSER_DISCARD_CHANGES=1 composer install --prefer-source --no-interaction

script:
  - vendor/bin/phpunit --coverage-text --verbose

after_script:
  - vendor/bin/test-reporter
